name: MacOS - Ngrok

on: workflow_dispatch

env:
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
  RDP_USER: admin
  RDP_PASS: p@ssw0rd!

defaults:
  run:
    shell: bash

jobs:
  ngrok-rdp:
    runs-on: macos-15
    timeout-minutes: 360
    steps:
      - name: Setup MacOS Remote Desktop
        run: |
          # Disable spotlight indexing
          sudo mdutil -i off -a
          
          # Disable sleep modes
          sudo systemsetup -setdisplaysleep Off
          sudo systemsetup -setsleep Off
          sudo systemsetup -setcomputersleep Off

          # Create new account
          sudo dscl . -create /Users/$RDP_USER
          sudo dscl . -create /Users/$RDP_USER UserShell /bin/bash
          sudo dscl . -create /Users/$RDP_USER RealName "$RDP_USER"
          sudo dscl . -create /Users/$RDP_USER UniqueID 1001
          sudo dscl . -create /Users/$RDP_USER PrimaryGroupID 80
          sudo dscl . -create /Users/$RDP_USER NFSHomeDirectory /Users/$RDP_USER
          sudo dscl . -passwd /Users/$RDP_USER $RDP_PASS
          
          sudo mkdir -p /Users/$RDP_USER
          sudo chown $VNC_USER:staff /Users/$RDP_USER
          sudo dscl . -append /Groups/admin GroupMembership $RDP_USER

          # Skip GUI login screen
          sudo defaults write /Library/Preferences/com.apple.loginwindow autoLoginUser -string "$RDP_USER"
          sudo defaults write /Library/Preferences/com.apple.loginwindow autoLoginUserScreen -string "0"

          # Disable SIP protections
          sudo nvram boot-args="serverperfmode=1 amfi_get_out_of_my_way=1 $(nvram boot-args 2>/dev/null | cut -f 2-)"

          # Enables osascript over SSH without keygen and fulldiskaccess warnings
          sudo defaults write com.apple.universalaccessAuthWarning /System/Applications/Utilities/Terminal.app -bool true
          sudo defaults write com.apple.universalaccessAuthWarning /usr/libexec -bool true
          sudo defaults write com.apple.universalaccessAuthWarning /usr/libexec/sshd-keygen-wrapper -bool true
          sudo defaults write com.apple.universalaccessAuthWarning com.apple.Terminal -bool true

          # Auto grant permissions
          EPOCH=$(($(date +'%s * 1000 + %-N / 1000000')))
          TCC="replace into access (service,client,client_type,auth_value,auth_reason,auth_version,indirect_object_identifier,flags,last_modified) values (\"kTCCServiceAccessibility\",\"/usr/sbin/sshd\",1,2,3,1,\"UNUSED\",0,$EPOCH);"
          sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "$TCC"
          sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "$TCC"

          # Enable VNC
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -allowAccessFor -allUsers -privs -all -clientopts -setvnclegacy -vnclegacy yes
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvncpw -vncpw "$RDP_PASS"
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -restart -agent -console

          # Turn off Bluetooth, if no paired devices exist
          sudo defaults write /Library/Preferences/com.apple.Bluetooth ControllerPowerState -int 0

          # Disable transparency in the menu bar and elsewhere
          defaults write com.apple.universalaccess reduceTransparency -bool true

          # Reduce Motion & Transparency
          defaults write com.apple.Accessibility DifferentiateWithoutColor -int 1
          defaults write com.apple.Accessibility ReduceMotionEnabled -int 1
          defaults write com.apple.universalaccess reduceMotion -int 1
          defaults write com.apple.universalaccess reduceTransparency -int 1
          defaults write com.apple.Accessibility ReduceMotionEnabled -int 1

          # Enable subpixel font rendering for non-Apple LCDs
          defaults write NSGlobalDomain AppleFontSmoothing -int 1

          # Enable Performance mode
          sudo nvram boot-args="serverperfmode=1 $(nvram boot-args 2>/dev/null | cut -f 2-)"

          # Enable Multi-Session
          sudo /usr/bin/defaults write .GlobalPreferences MultipleSessionsEnabled -bool TRUE
          defaults write "Apple Global Domain" MultipleSessionsEnabled -bool true

          # Disable Screen-Lock
          defaults write com.apple.loginwindow DisableScreenLock -bool true
          defaults write com.apple.loginwindow AllowList -string '*'

          # Disables automatic termination of inactive apps
          defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

          # Disable automatic log-out
          sudo defaults write GlobalPreferences com.apple.autologout.AutoLogOutDelay 0

          # Disable display sleep and disable screensaver password
          sudo pmset -a displaysleep 0
          sudo defaults write /Library/Preferences/com.apple.screensaver askForPassword -int 0

          # Disable save to iCloud
          sudo defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
          
          # Disable the iCloud prompt when you login
          sudo defaults write "/System/Library/User Template/Non_localized/Library/Preferences/com.apple.SetupAssistant" DidSeeCloudSetup -bool TRUE

          # Save to disk (not to iCloud) by default:
          defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false

          # Disables reading/writing .DS_Stores on SMB network shares
          # @see https://support.apple.com/en-us/HT208209
          defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

          # Keep the session alive (caffeinate prevents idle sleep)
          caffeinate -dimsu &>/dev/null &

      - name: Install and Configure Ngrok
        run: |
          curl -s https://bin.equinox.io/a/bwQ25LiJJwv/ngrok-v3-3.23.3-darwin-arm64.zip -o ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok
          ./ngrok authtoken $NGROK_AUTH_TOKEN

      - name: Start Ngrok Tunnel
        run: |
          max_retries=3
          retry_count=0
          success=false

          while [ $success = false ] && [ $retry_count -lt $max_retries ]; do
            ./ngrok tcp 5900 &
            ngrok_pid=$!

            attempts=0
            max_attempts=10
            ngrok_url=""
            while [ -z "$ngrok_url" ] && [ $attempts -lt $max_attempts ]; do
              sleep 5
              attempts=$((attempts + 1))
              ngrok_url=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[] | select(.proto == "tcp") | .public_url' 2>/dev/null)
            done

            if [ -z "$ngrok_url" ]; then
              echo "Failed to retrieve Ngrok URL after $max_attempts attempts."
              retry_count=$((retry_count + 1))
              kill $ngrok_pid
              continue
            fi

            ngrok_url=${ngrok_url#tcp://}
            address=${ngrok_url%:*}
            port=${ngrok_url#*:}

            if nc -z -w 5 $address $port; then
              success=true
              echo "VNC Connection Details"
              echo "URL: $address:$port"
              echo "Username: $RDP_USER"
              echo "Password: $RDP_PASS"
            else
              echo "Connection test failed. Retrying..."
              kill $ngrok_pid
              retry_count=$((retry_count + 1))
              sleep 5
            fi
          done

          if [ $success = false ]; then
            echo "Failed to establish a working Ngrok tunnel after $max_retries attempts."
            exit 1
          fi

      - name: Keep Alive
        run: |
          duration=21600  # 6 hours in seconds
          interval=300    # 5 minutes in seconds
          end_time=$(( $(date +%s) + duration ))

          while [ $(date +%s) -lt $end_time ]; do
            if ! pgrep -f "./ngrok tcp 5900" > /dev/null; then
              echo "Ngrok process not found. Exiting workflow."
              exit 1
            fi
            sleep $interval
          done

      - name: Cleanup
        if: always()
        run: |
          if pgrep -f "./ngrok tcp 5900" > /dev/null; then
            echo "Terminating Ngrok process..."
            pkill -f "./ngrok tcp 5900"
          fi
          echo "Cleanup complete."
