name: macOS - Ngrok

on: workflow_dispatch

env:
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
  RDP_USER: admin
  RDP_PASS: p@ssw0rd!

defaults:
  run:
    shell: bash

jobs:
  ngrok-rdp:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: Setup MacOS Remote Desktop
        run: |
          echo "▶️ Disabling Spotlight indexing..."
          sudo mdutil -i off -a

          echo "👤 Creating user: $RDP_USER"
          sudo dscl . -create /Users/$RDP_USER
          sudo dscl . -create /Users/$RDP_USER UserShell /bin/bash
          sudo dscl . -create /Users/$RDP_USER RealName "$RDP_USER"
          sudo dscl . -create /Users/$RDP_USER UniqueID 1001
          sudo dscl . -create /Users/$RDP_USER PrimaryGroupID 80
          sudo dscl . -create /Users/$RDP_USER NFSHomeDirectory /Users/$RDP_USER
          sudo dscl . -passwd /Users/$RDP_USER "$RDP_PASS"
          sudo createhomedir -c -u $RDP_USER > /dev/null

          echo "🖥 Enabling Remote Management..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -users $RDP_USER \
            -privs -all -restart -agent -menu

          echo "🔐 Setting VNC password..."
          echo -n "$RDP_PASS" | perl -we '
            BEGIN { @k = unpack "C*", pack "H*", "1734516E8BA8C5E2FF1C39567390ADCA" };
            $_ = <>; chomp; s/^(.{8}).*/$1/;
            @p = unpack "C*", $_;
            foreach (@k) { printf "%02X", $_ ^ (shift @p || 0) }; print "\n"
          ' | sudo tee /Library/Preferences/com.apple.VNCSettings.txt > /dev/null
          sudo chmod 600 /Library/Preferences/com.apple.VNCSettings.txt

          echo "🎛 Optimizing settings..."
          defaults write com.apple.Accessibility ReduceMotionEnabled -int 1
          defaults write com.apple.universalaccess reduceMotion -int 1
          defaults write com.apple.universalaccess reduceTransparency -int 1
          sudo nvram boot-args="serverperfmode=1 $(nvram boot-args 2>/dev/null | cut -f 2-)"

          echo "🔓 Disabling screen lock..."
          defaults write com.apple.loginwindow DisableScreenLock -bool true
          defaults write com.apple.loginwindow AllowList -string '*'

          cd /Users/$RDP_USER || cd ~

      - name: Install and Configure Ngrok
        run: |
          brew install --cask ngrok
          ngrok config add-authtoken "$NGROK_AUTH_TOKEN"

      - name: Start Ngrok Tunnel
        run: |
          ngrok tcp 5900 --log=stdout > ngrok.log &
          sleep 10

          TUNNEL_URL=""
          for i in {1..10}; do
            TUNNEL_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[] | select(.proto == "tcp") | .public_url')
            if [[ -n "$TUNNEL_URL" ]]; then
              break
            fi
            echo "Waiting for ngrok tunnel..."
            sleep 5
          done

          if [[ -z "$TUNNEL_URL" ]]; then
            echo "Failed to get Ngrok tunnel URL"
            exit 1
          fi

          TUNNEL_URL=${TUNNEL_URL#tcp://}
          HOST=${TUNNEL_URL%:*}
          PORT=${TUNNEL_URL##*:}

          echo "✅ RDP/VNC Tunnel Established!"
          echo "🔗 Connect to: $HOST:$PORT"
          echo "👤 Username: $RDP_USER"
          echo "🔒 Password: $RDP_PASS"

      - name: Setup tmate Session
        uses: mxschmitt/action-tmate@v3

      - name: Keep Alive (6 hours)
        run: |
          echo "Keeping runner alive for 6 hours..."
          for i in {1..72}; do
            echo "Still alive... ($i)"
            sleep 300
          done

      - name: Cleanup Ngrok
        if: always()
        run: |
          pkill ngrok || true
          echo "Ngrok process cleaned up."
