name: Windows - Ngrok

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive -Path ngrok.zip -DestinationPath .

    - name: Authenticate ngrok
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Password for runneradmin
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start ngrok
      run: Start-Process -NoNewWindow -FilePath .\ngrok.exe -ArgumentList "tcp 3389" -PassThru

    - name: Wait for ngrok to start
      run: Start-Sleep -Seconds 5

    - name: Get ngrok tunnel information
      run: |
        $maxAttempts = 20
        $attempts = 0
        $ngrokApi = $null

        while (($null -eq $ngrokApi) -and ($attempts -lt $maxAttempts)) {
          $attempts += 1
          try {
            $ngrokApi = Invoke-WebRequest -Uri "http://localhost:4040/api/tunnels"
          } catch {
            Write-Host "Waiting for ngrok API... (attempt $attempts of $maxAttempts)"
            Start-Sleep -Seconds 5
          }
        }

        if ($null -eq $ngrokApi) {
          throw "Failed to connect to ngrok API after $maxAttempts attempts."
        }

        $ngrokUrl = ($ngrokApi.Content | ConvertFrom-Json).tunnels[0].public_url
        Write-Host "Ngrok URL: $ngrokUrl"

    - name: Wait before cleanup
      run: Start-Sleep -Hours 6

    - name: Cleanup
      if: always()
      run: |
        $ngrokProcess = Get-Process -Name "ngrok" -ErrorAction SilentlyContinue
        if ($null -ne $ngrokProcess) {
          Write-Host "Terminating ngrok process..."
          $ngrokProcess | Stop-Process -Force
        } else {
          Write-Host "Ngrok process not found."
        }
